const { EntitySchema } = require("typeorm");

const Client = new EntitySchema({
  name: "Client",
  tableName: "clients",
  columns: {
    id: { primary: true, type: "int", generated: true },
    numero: { type: "int", nullable: true },
    raison_sociale: { type: "varchar", length: 100, nullable: true },
    designation: { type: "varchar", length: 100, nullable: true },
    matricule_fiscal: { type: "varchar", length: 50, nullable: true },
    register_commerce: { type: "varchar", length: 50, nullable: true },
    adresse: { type: "varchar", length: 200, nullable: true },
    ville: { type: "varchar", length: 50, nullable: true },
    code_postal: { type: "varchar", length: 10, nullable: true },
    telephone1: { type: "varchar", length: 20, nullable: true },
    telephone2: { type: "varchar", length: 20, nullable: true },
    telephone3: { type: "varchar", length: 20, nullable: true },
    telephone4: { type: "varchar", length: 20, nullable: true },
    email: { type: "varchar", length: 100, nullable: true },
    site_web: { type: "varchar", length: 100, nullable: true },
    commentaire: { type: "text", nullable: true },
    nature: { type: "int", nullable: true },
    timbre: { type: "int", nullable: true },
    exonere: { type: "int", nullable: true },
    permanent: { type: "int", nullable: true },
    solde: { type: "decimal", precision: 10, scale: 2, nullable: true },
    tau_rem: { type: "int", nullable: true },
    passager: { type: "int", nullable: true },
    status: {
      type: "enum",
      enum: ["Actif", "Inactif"],
      default: "Actif",
    },
    poste: { type: "varchar", length: 50, nullable: true },
    utilisateur: { type: "varchar", length: 50, nullable: true },
    date_creation: { type: "date", nullable: true },
    date_maj: { type: "date", nullable: true },
    heure_maj: { type: "time", nullable: true },
    path_sigle: { type: "varchar", length: 200, nullable: true },
    sigle: { type: "varchar", length: 50, nullable: true },
    createdAt: { type: "timestamp", createDate: true },
    updatedAt: { type: "timestamp", updateDate: true },
  },
});

module.exports = { Client };
